import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="he" dir="ltr">
      <body dir="rtl" className="antialiased text-zinc-100 overflow-x-hidden">
        <main className="container min-h-[var(--app-height)]">{children}</main>
      </body>
    </html>
  );
}
